// Functions
#define KSYM_FUNC(func) \
  int func() { return 0; }

KSYM_FUNC(bpf_get_current_pid_tgid)
KSYM_FUNC(bpf_trace_printk)
KSYM_FUNC(bpf_map_lookup_elem)
KSYM_FUNC(bpf_map_update_elem)
KSYM_FUNC(bpf_map_delete_elem)
KSYM_FUNC(bpf_map_push_elem)
KSYM_FUNC(bpf_map_pop_elem)
KSYM_FUNC(bpf_map_peek_elem)
KSYM_FUNC(bpf_probe_read_kernel)
KSYM_FUNC(ktime_get_mono_fast_ns)
KSYM_FUNC(ktime_get_boot_fast_ns)
KSYM_FUNC(get_random_u32)
KSYM_FUNC(bpf_snprintf)
KSYM_FUNC(vprintk)
KSYM_FUNC(rex_landingpad)
KSYM_FUNC(bpf_spin_lock)
KSYM_FUNC(bpf_spin_unlock)
KSYM_FUNC(just_return_func)
KSYM_FUNC(bpf_get_stackid_pe)
KSYM_FUNC(bpf_perf_prog_read_value)
KSYM_FUNC(bpf_perf_event_output_tp)
KSYM_FUNC(bpf_perf_event_read_value)
KSYM_FUNC(bpf_skb_event_output)
KSYM_FUNC(bpf_xdp_event_output)
KSYM_FUNC(bpf_xdp_adjust_head)
KSYM_FUNC(bpf_xdp_adjust_tail)
KSYM_FUNC(bpf_clone_redirect)
KSYM_FUNC(bpf_ringbuf_output)
KSYM_FUNC(bpf_ringbuf_reserve)
KSYM_FUNC(bpf_ringbuf_submit)
KSYM_FUNC(bpf_ringbuf_discard)
KSYM_FUNC(bpf_ringbuf_query)
KSYM_FUNC(bpf_ktime_get_ns)
KSYM_FUNC(bpf_ktime_get_boot_ns)
KSYM_FUNC(bpf_ktime_get_coarse_ns)
KSYM_FUNC(rex_trace_printk)
KSYM_FUNC(bpf_task_from_pid)
KSYM_FUNC(bpf_task_release)
KSYM_FUNC(scx_bpf_dsq_insert)
KSYM_FUNC(scx_bpf_select_cpu_dfl)
KSYM_FUNC(scx_bpf_dsq_move_to_local)
KSYM_FUNC(scx_bpf_kick_cpu)
KSYM_FUNC(scx_bpf_create_dsq)
KSYM_FUNC(scx_bpf_destroy_dsq)
KSYM_FUNC(scx_bpf_task_cpu)
KSYM_FUNC(scx_bpf_error_bstr)
KSYM_FUNC(scx_bpf_dsq_insert_vtime)
KSYM_FUNC(scx_bpf_dispatch_nr_slots)
KSYM_FUNC(scx_bpf_dispatch_cancel)
KSYM_FUNC(scx_bpf_dsq_nr_queued)
KSYM_FUNC(scx_bpf_task_set_slice)
KSYM_FUNC(scx_bpf_task_set_dsq_vtime)
KSYM_FUNC(scx_bpf_reenqueue_local)
KSYM_FUNC(scx_bpf_nr_cpu_ids)
KSYM_FUNC(bpf_iter_scx_dsq_new)
KSYM_FUNC(bpf_iter_scx_dsq_next)
KSYM_FUNC(bpf_iter_scx_dsq_destroy)
KSYM_FUNC(__scx_bpf_dsq_insert_vtime)
KSYM_FUNC(__scx_bpf_select_cpu_and)
KSYM_FUNC(scx_bpf_dsq_insert___v2)
KSYM_FUNC(scx_bpf_reenqueue_local___v2)
KSYM_FUNC(scx_bpf_dsq_move_set_slice)
KSYM_FUNC(scx_bpf_dsq_move_set_vtime)
KSYM_FUNC(scx_bpf_dsq_move)
KSYM_FUNC(scx_bpf_dsq_move_vtime)
KSYM_FUNC(scx_bpf_dsq_peek)
KSYM_FUNC(scx_bpf_exit_bstr)
KSYM_FUNC(scx_bpf_dump_bstr)
KSYM_FUNC(scx_bpf_cpuperf_cap)
KSYM_FUNC(scx_bpf_cpuperf_cur)
KSYM_FUNC(scx_bpf_cpuperf_set)
KSYM_FUNC(scx_bpf_nr_node_ids)
KSYM_FUNC(scx_bpf_get_possible_cpumask)
KSYM_FUNC(scx_bpf_get_online_cpumask)
KSYM_FUNC(scx_bpf_put_cpumask)
KSYM_FUNC(scx_bpf_task_running)
KSYM_FUNC(scx_bpf_cpu_rq)
KSYM_FUNC(scx_bpf_locked_rq)
KSYM_FUNC(scx_bpf_cpu_curr)
KSYM_FUNC(scx_bpf_task_cgroup)
KSYM_FUNC(scx_bpf_now)
KSYM_FUNC(scx_bpf_events)
KSYM_FUNC(scx_bpf_cpu_node)
KSYM_FUNC(scx_bpf_select_cpu_and)
KSYM_FUNC(scx_bpf_get_idle_cpumask_node)
KSYM_FUNC(scx_bpf_get_idle_cpumask)
KSYM_FUNC(scx_bpf_get_idle_smtmask_node)
KSYM_FUNC(scx_bpf_get_idle_smtmask)
KSYM_FUNC(scx_bpf_put_idle_cpumask)
KSYM_FUNC(scx_bpf_test_and_clear_cpu_idle)
KSYM_FUNC(scx_bpf_pick_idle_cpu_node)
KSYM_FUNC(scx_bpf_pick_idle_cpu)
KSYM_FUNC(scx_bpf_pick_any_cpu_node)
KSYM_FUNC(scx_bpf_pick_any_cpu)

// Global variables
unsigned long jiffies;
int numa_node;
void *rex_cleanup_entries;
unsigned long rex_stack_ptr;
void *current_task;
int cpu_number;
unsigned char rex_termination_state;
unsigned long this_cpu_off;
char *rex_log_buf;
